apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ template "ingress-route.fullname" . }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ template "ingress-route.name" . }}
    helm.sh/chart: {{ template "ingress-route.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    {{- range $entryPoint := .Values.entryPoints }}
    - {{$entryPoint}}
    {{- end }}  
  routes:
  - match: Host(`{{ .Values.publicHost }}`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
    middlewares:
      {{- with .Values.middlewares }}
      {{- toYaml . | nindent 4 }}
      {{- end }}